# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18a192545e376f1a15facc45e30303db955d038a14df1f65cea811a6e1e7d3ee071323d54a2415ff7e0f25ec7ee30d2878607c6a2a9eb220e139ff37cdd8c68

test:
  secret_key_base: 35ed2c1f40925737eb5dd81ee21372115ddc95e75a4482d0f71108fe9e30ff6b0e6b6cd91aa708fd35689efb0c68907077c66c88746f045a8a8476998342bdf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
